import Head from "next/head";
import Link from "next/link";

import {
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
} from "@ant-design/icons";
import React, { useState } from "react";
import { Layout, Button } from "antd";
const { Header, Sider, Content } = Layout;
import { HeaderComponent, SidebarComponent } from "../components";
import { getUser } from "../api/user";
const Home = () => {
  const [collapsed, setCollapsed] = useState(false);
  const doTest = async () => {
    const data = await getUser();
    console.log(data);
  };
  return (
    <>
      <HeaderComponent />
      <Layout>
        <Sider
          trigger={null}
          collapsible
          collapsed={collapsed}
          style={{ flex: "none" }}
        >
          <SidebarComponent />
        </Sider>
        <Layout className="site-layout">
          <Content
            className="site-layout-background"
            style={{
              margin: "24px 16px",
              padding: 24,
              minHeight: 280,
            }}
          >
            <Button onClick={doTest}>123</Button>
          </Content>
        </Layout>
      </Layout>
    </>
  );
};

export default Home;

// export default function Home() {
//   return (
//     <div>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <Header />
//       <Content />
//       <Footer />
//     </div>
//   );
// }
